### PR TITLE
Fixes Bug: TokenForm fetchItems

### LINKED ISSUE #25: Bug: TokenForm fetchItems
During the PR review process, fetchItems was removed in TokenForm. Due to this, there is no longer validation of the tokens. Please add fetchItems back into TokenForm so that there is token validation.

AC - 
As a user, when I add a token which already exists in the database then I will see an error.

### PR DESCRIPTION
**Pull request by aidantorrence**
FetchItems wasn't being called after previous PR.  fetchItems is added back so that the form validation logic works.

## Related Issue

closes #25 

## Acceptance Criteria

- [ ] as a user, when I add a token which already exists in the database then I will see an error.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
|   | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

=> existing token produces error on click
image

### After

=> existing token does not produce error on click

### CODE REVIEW

File: src/TokenForm.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ const TokenForm = () => {
       });
       return unsubscribe;
     };
-
+    fetchItems();
```
Comment (MikeBLambert) [inline src/TokenForm.js:30]: Ah, ok...so it wasn't fully removed, but just not invoked.

So, for the memory leak, what I think that you actually want to do is return `unsubscribe`. However, because `unsubscribe` is initialized inside of a `fetchItems` you'll need to assign it to a variable initialized in the outer body of the function. Typically, for reassignment in React, we use [refs](https://reactjs.org/docs/refs-and-the-dom.html). 
In this case, I'd recommend that rather than returning `fetchItems` at the end, you should do something like:

```javascript
const unsubscribeRef = useRef();

useEffect(() => {
    const fetchItems = async () => {
      const response = collection(db, 'shopping-list');
      const itemList = query(response);
      const unsubscribe = onSnapshot(itemList, (querySnapshot) => {
        const tokens = querySnapshot.docs.reduce((acc, doc) => {
          const { userToken } = doc.data();
          return [...acc, userToken];
        }, []);
        console.log('tokens: ', tokens);
        setTokens(tokens);
      });
      return unsubscribe;
    };
    fetchItems();
    return unsubscribeRef.current;
}, [db]);
```

Comment (gabynr) [reply src/TokenForm.js:29]: Thank you Aidan for doing the change and thank you, Mike, for telling us how to fix the issue!! Now it is working

**Review by gabynr — APPROVED** [review]
Thank you Aidan for doing the change and thank you, Mike, for telling us how to fix the issue!! Now it is working. 👏🏽😊

**Review by MikeBLambert — APPROVED** [review]
great job!
